name: Build Kaseb APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          
      # حذف پوشه تست جهت عبور از خطای ویجت‌ها
      - name: Remove Test Folder
        run: rm -rf test
        
      # بازسازی خودکار ساختار اندروید با نام حروف کوچک kaseb
      - name: Recreate Android Project Structure
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name=kaseb
          
      - name: Force Fix Android MinSdkVersion to 21
        run: |
          echo "flutter.minSdkVersion=21" >> android/local.properties
          sed -i 's/minSdkVersion .*/minSdkVersion 21/g' android/app/build.gradle || true
          sed -i 's/minSdkVersion = .*/minSdkVersion = 21/g' android/app/build.gradle || true
          
      - run: flutter pub get
      
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses || true
      
      # کامپایل یکپارچه و صعود مقتدرانه به خروجی نهایی APK
      - run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kaseb-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
